### ISSUE TITLE
Wiki completely lost after successful conversion

### ISSUE THREAD

**Issue by milanbx** [orchitech/redmine_reformat#4]
Hi, I am using Redmine 4.2.0.stable and I have started to run converter with a dry one first, then a normal run, everything seemed OK, all threads ended successfully, however, complete wiki content was gone.  Any idea, why?
I have converted from Textile to Markdown. Converter plugin is 0.7.0-pre.
Thanks for help.

**Comment by martincizek** [comment]
Is it only wiki content? Is there anything that is converted successfully?

The first idea is that there is something weird with pandoc invocation, but that would affect all conversions.

**Comment by martincizek** [comment]
I've just tried it with clean Redmine and works as expected. My steps:
1. `docker run --name rmtest -p 3000:3000 redmine:4.2.0`
2. log in, load default setup, create a new project, create a wiki page
3. `docker exec -it rmtest bash`
4. `apt-get update && apt-get install vim gcc make less pandoc`
5. `git -C plugins clone https://github.com/orchitech/redmine_reformat.git`
6. `bundle install`
7. `rake reformat:convert to_formatting=markdown` (parallel processing does not work with sqlite)
8. checked Redmine and all OK (text formatting changed to "markdown", welcome text converted, wiki page converted)

I'm afraid I don't have any info to analyse what happened in your case.

Please make sure that it works in some test setup first - as above.

And you can always use an auxiliary Redmine installation (like the docker mentioned above) and run it agains your database. You can then drop the auxiliary Redmine installation and proceed with your normal Redmine instance and the converted database.

Don't forget to back up your data in any case. :)

**Comment by milanbx** [comment]
ok, thnx, especially for the procedure, I will try my best.

**Comment by milanbx** [comment]
I will check on the non-wiki conversions too. And will provide feedback in case of any progress or even success.

**Comment by milanbx** [comment]
Well, now it is sure, that not only wiki pages disappear, but also home page welcome text, issue description, issue comments, news, simply all RTF content, even if it was not RTF at all. Please see attached log.
[convert-log.txt](https://github.com/orchitech/redmine_reformat/files/6716730/convert-log.txt)

**Comment by pavelhoral** [comment]
Just want to jump in with a simple observation that the log is full of this:

> pandoc: unrecognized option `--wrap=preserve'

This option has been added in Pandoc 2.9.1 - https://pandoc.org/releases.html#pandoc-2.9.1-2019-12-23 .

**Comment by martincizek** [comment]
> even if it was not RTF at all.

Well, non-RTF content of a RTF field is still RTF. :-) If this was true, issue subjects would disappear too, which I hope was not the case.

> This option has been added in Pandoc 2.2 so maybe you are using some older version?

This seems to be the case. `redmine_reformat` is confirmed to work with pandoc versions from `2.2.1` (Debian 10) to at least `2.9.2`.

You can install a newer version directly from pandoc releases, e.g. `wget -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb  && dpkg -i /tmp/pandoc.deb` for Debian. More at https://github.com/jgm/pandoc/releases.

**Comment by milanbx** [comment]
unfortunately, this is the case meaning the issue subject disappears too. I will try to reinstall the pandoc to the described version. thank you.

**Comment by martincizek** [comment]
P.S. It's indeed possible to remove the `--wrap=preserve` option, but I'd suggest against it, as there were some issues with older pandoc versions, including that it was freezing for certain inputs.

**Comment by milanbx** [comment]
ok understood, will not try. any other options what to do?

**Comment by martincizek** [comment]
> ok understood, will not try. any other options what to do?

Using newer pandoc is not possible?

**Comment by martincizek** [comment]
> unfortunately, this is the case meaning the issue subject disappears too. I will try to reinstall the pandoc to the described version. thank you.

This is quite weird. I am able to reproduce "disappearing" RTF contents when I replace `pandoc` with `/bin/false` (the error is only detected if SIGPIPE occurs, which is a bug). But the issue subject was preserved.

**Comment by milanbx** [comment]
well, a hosted environment (managed VPS) is used in this case, so I have to check the pandoc version with the support team.

**Comment by martincizek** [comment]
Well, you can indeed try to remove `--wrap=preserve`, just the result might not be optimal. I meant that updating pandoc is preferred over removing the unsupported option. :-)

**Comment by martincizek** [comment]
Updated the plugin. The current version technically fixes this issue - the conversion will be aborted on pandoc invocation failure.

If you want to try it with the unsupported old pandoc version, just delete the line containing `--wrap=preserve` in `lib/redmine_reformat/converters/textile_to_markdown/converter.rb`.

**Comment by milanbx** [comment]
thanks a lot, I will try that and let you know the results.

**Comment by milanbx** [comment]
The pandoc version is 2.14.0.3 and I have updated your plugin to the latest version, as advised. Nothing else changed.
And the conversion failed on several errors - see log pls.
[log.txt](https://github.com/orchitech/redmine_reformat/files/6720151/log.txt)

**Comment by martincizek** [comment]
> ` :workers=>10,`

There is not much data in your instance, so it's better not to use parallel invocation. It doesn't matter if all goes well. But if there is an issue, all non-failed workers continue to run until the final rendez-vous, so the log is a mess in the end. :)

> [ERROR] Issue#18: /issues/18 - pandoc execution timeout

It's kind of weird that **all** `pandoc` invocations ended with a timeout. Can you please try it by hand?
Just copy&paste source code of e.g. issue 18's description, save it to `/tmp/18.textile` and run:
``` console
$ time pandoc --wrap=preserve -f  textile-smart -t gfm < /tmp/18.textile > /tmp/18.md
$ echo $? # check exit code
```

**Comment by martincizek** [comment]
P.S.:
* Also make sure that you capture both STDOUT and STDERR when capturing the output (`> log.txt 2>&1`)
* This might be an effect of mandatory access control (like SELinux or AppArmor). In that case, the best solution would be to take the database and run the migration in another Redmine instance in unrestricted environment (it can be even a simple Docker installation on your local desktop, as suggested above). When you are satisfied with the result, you can dump the migrated DB and bring it back to the server.

**Comment by milanbx** [comment]
OK. I am no expert at all, but I will try my best. And I am also completely untouched by Docker paradigm. Thanks a lot.

**Comment by martincizek** [comment]
> OK. I am no expert at all, but I will try my best. And I am also completely untouched by Docker paradigm. Thanks a lot.

Fingers crossed. It should be as easy as following the instructions in [Docker HUB](https://hub.docker.com/_/redmine) and proceed with instructions in coment https://github.com/orchitech/redmine_reformat/issues/4#issuecomment-868404870.

Still I'm quite curious about what happened in your case - so that we can instruct other users about the eventual issue. So if I may ask, please:
* Test the `pandoc` as suggested in comment https://github.com/orchitech/redmine_reformat/issues/4#issuecomment-869556839 - and post the output.
* Try to run the conversion without parallelism and post your output, e.g.:\
   `rake reformat:convert to_formatting=markdown 2>&1 | tee /tmp/reformat-log.txt`

It's indeed possible to increase the timeout `lib/redmine_reformat/converters/textile_to_markdown/converter.rb` if it was an issue for a particular record, but currently it seems there is something more fundamental (which can even be that there are not enough resources for 10 workers :)).

**Comment by milanbx** [comment]
No sure, how I did it, but all done OK now. Knowingly, I have just skipped the parallel workers.
Anyway, thanks for help!!!
