### ISSUE TITLE
undefined method error when converting textile to markdown 

### ISSUE THREAD

**Issue by NecroX6** [orchitech/redmine_reformat#8]
Hi

I have Redmine 4.2.2, ruby 2.7.4, and pandoc 2.14.2
When i run `rake reformat:convert to_formatting=markdown dryrun=1 --trace` i get this error

`rake aborted!
NameError: undefined method `extend_object' for class `Singleton'
Did you mean?  extended
/usr/share/ruby/singleton.rb:150:in `undef_method'
/usr/share/ruby/singleton.rb:150:in `singleton class'
/usr/share/ruby/singleton.rb:138:in `<module:Singleton>'
/usr/share/ruby/singleton.rb:94:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/deprecation.rb:3:in `require'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/deprecation.rb:3:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/inflector/inflections.rb:7:in `require'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/inflector/inflections.rb:7:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/inflections.rb:3:in `require'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/inflections.rb:3:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:3:in `require'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/dependencies/autoload.rb:3:in `require'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support/dependencies/autoload.rb:3:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support.rb:27:in `require'
/usr/local/share/gems/gems/activesupport-5.2.6/lib/active_support.rb:27:in `<top (required)>'
/usr/local/share/gems/gems/railties-5.2.6/lib/rails.rb:7:in `require'
/usr/local/share/gems/gems/railties-5.2.6/lib/rails.rb:7:in `<top (required)>'
/var/www/html/config/application.rb:5:in `require'
/var/www/html/config/application.rb:5:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
/var/www/html/Rakefile:5:in `<top (required)>'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/share/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>`

**Comment by martincizek** [comment]
Closing due to lack of feedback.
